### ISSUE TITLE
ESP32 port.

### ISSUE THREAD

**Issue by GabeHC** [gnulabis/UTFT-ESP8266#15]
Great job, Can you make it ESP32 compitable?

**Comment by gnulabis** [comment]
Hi, thanks.

Not really, not now anyway, since I don't have the hardware to test it.

**Comment by Cristianistrate** [comment]
Any news on ESP32 Port ?

**Comment by gnulabis** [comment]
Hi, no, unfortunately I still don't have an ESP32.

**Comment by Osmosis311** [comment]
I'm sure the community would be happy to send you one.  Adafruit has an ESP32 "Feather" board for only $20.

**Comment by gnulabis** [comment]
Well, I had to order a new TFT module, so I ordered a NodeMCU ESP32 module as well.

Stay tuned...

**Comment by gnulabis** [comment]
I just pushed 3ebc408c2d9cbe038315b996199eb85a2f7e7175, which adds preliminary support for ESP32. I briefly tested it with hardware SPI and it works. I'll merge it to master once I've done a few more tests.

For the record, I used the following wiring in my test (and the VSPI port pins for SPI clock and data):
`UTFT myGLCD ( ILI9341_S5P, 5, 16, 4 ); `
