### ISSUE TITLE
Important note for adding additional fonts from Rinkydinkelectronics.com

### ISSUE THREAD

**Issue by Tonyknz** [gnulabis/UTFT-ESP8266#23]
If you wish to use additional fonts from RinkyDinkElectronics with this library on an ESP8266 or ESP32 you need to add the following lines into the device selection section of the [fontname].c file as follows.

#elif defined(ESP8266) || defined(ESP32)
        #include <Arduino.h>
        #include <pgmspace.h>
        #define fontdatatype const uint8_t
#endif

This code can be found within the DefaultFonts.c file included within this build.

**Comment by gnulabis** [comment]
Thanks. I've decided to create a FAQ wiki page and I added this info there.

https://github.com/gnulabis/UTFT-ESP/wiki/FAQ#how-to-add-a-new-custom-font-definition
